<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.edit',
            'users.delete',
            'users.restore',
            'users.change-password',
            'users.assign-roles',
            'fingerprint-templates.view',
            'fingerprint-templates.create',
            'fingerprint-templates.update',
            'fingerprint-templates.delete',
            'roles.view',
            'roles.create',
            'roles.edit',
            'roles.delete',
            'roles.assign-permissions',
            'permissions.view',
            'permissions.create',
            'permissions.edit',
            'permissions.delete',
            'companies.view',
            'companies.create',
            'companies.update',
            'companies.delete',
            'seasons.view',
            'seasons.create',
            'seasons.update',
            'seasons.delete',
            'divisions.view',
            'divisions.create',
            'divisions.update',
            'divisions.delete',
            'courts.view',
            'courts.create',
            'courts.update',
            'courts.delete',
            'teams.view',
            'teams.create',
            'teams.update',
            'teams.delete',
            'teams.approve-updates',
            'players.view',
            'players.create',
            'players.update',
            'players.delete',
            'player-imports.view',
            'player-imports.create',
            'tournaments.view',
            'tournaments.create',
            'tournaments.update',
            'tournaments.delete',
            'tournament-registrations.view',
            'tournament-registrations.create',
            'tournament-registrations.update',
            'tournament-registrations.delete',
            'fixtures.view',
            'fixtures.generate',
            'matchdays.view',
            'matchdays.create',
            'matchdays.update',
            'match-reports.view',
            'match-reports.update',
            'match-reports.reopen',
            'standings.view',
            'standings.adjust',
            'accreditations.view',
            'accreditations.update',
            'player-habilitations.view',
            'player-habilitations.create',
            'player-habilitations.update',
            'player-habilitations.delete',
            'player-transfers.view',
            'player-transfers.create',
            'player-transfers.review',
            'player-transfers.settings',
            'league-settings.view',
            'league-settings.update',
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.delete',
            'audits.view',
        ];

        foreach ($permissions as $permission) {
            Permission::findOrCreate($permission);
        }

        Permission::query()
            ->whereNotIn('name', $permissions)
            ->delete();

        Role::findOrCreate('super_admin')->syncPermissions($permissions);
        Role::findOrCreate('admin')->syncPermissions(array_values(array_diff($permissions, ['teams.approve-updates', 'match-reports.reopen', 'standings.adjust'])));

        Role::findOrCreate('manager')->syncPermissions([
            'dashboard.view',
            'users.view',
            'fingerprint-templates.view',
            'fingerprint-templates.create',
            'fingerprint-templates.update',
            'roles.view',
            'permissions.view',
            'companies.view',
            'companies.create',
            'companies.update',
            'seasons.view',
            'seasons.create',
            'seasons.update',
            'divisions.view',
            'divisions.create',
            'divisions.update',
            'courts.view',
            'courts.create',
            'courts.update',
            'teams.view',
            'teams.create',
            'teams.update',
            'players.view',
            'players.create',
            'players.update',
            'player-imports.view',
            'player-imports.create',
            'tournaments.view',
            'tournaments.create',
            'tournaments.update',
            'tournament-registrations.view',
            'tournament-registrations.create',
            'tournament-registrations.update',
            'fixtures.view',
            'fixtures.generate',
            'matchdays.view',
            'matchdays.create',
            'matchdays.update',
            'match-reports.view',
            'match-reports.update',
            'standings.view',
            'accreditations.view',
            'accreditations.update',
            'player-habilitations.view',
            'player-habilitations.create',
            'player-habilitations.update',
            'player-transfers.view',
            'player-transfers.create',
            'player-transfers.settings',
            'league-settings.view',
            'league-settings.update',
            'categories.view',
            'categories.create',
            'categories.update',
            'audits.view',
        ]);

        Role::findOrCreate('viewer')->syncPermissions([
            'dashboard.view',
            'users.view',
            'fingerprint-templates.view',
            'roles.view',
            'permissions.view',
            'companies.view',
            'seasons.view',
            'divisions.view',
            'courts.view',
            'teams.view',
            'players.view',
            'player-imports.view',
            'tournaments.view',
            'tournament-registrations.view',
            'fixtures.view',
            'matchdays.view',
            'match-reports.view',
            'standings.view',
            'accreditations.view',
            'player-habilitations.view',
            'player-transfers.view',
            'league-settings.view',
            'categories.view',
            'audits.view',
        ]);

        app()[PermissionRegistrar::class]->forgetCachedPermissions();
    }
}
