<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();
        $guard = 'web';

        $permissions = [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.edit',
            'users.delete',
            'users.restore',
            'users.change-password',
            'users.assign-roles',
            'fingerprint-templates.view',
            'fingerprint-templates.create',
            'fingerprint-templates.update',
            'fingerprint-templates.delete',
            'roles.view',
            'roles.create',
            'roles.edit',
            'roles.delete',
            'roles.assign-permissions',
            'permissions.view',
            'permissions.create',
            'permissions.edit',
            'permissions.delete',
            'database-backups.view',
            'database-backups.create',
            'database-backups.restore',
            'database-backups.delete',
            'companies.view',
            'companies.create',
            'companies.update',
            'companies.delete',
            'seasons.view',
            'seasons.create',
            'seasons.update',
            'seasons.delete',
            'divisions.view',
            'divisions.create',
            'divisions.update',
            'divisions.delete',
            'courts.view',
            'courts.create',
            'courts.update',
            'courts.delete',
            'teams.view',
            'teams.create',
            'teams.update',
            'teams.delete',
            'teams.approve-updates',
            'players.view',
            'players.create',
            'players.update',
            'players.delete',
            'player-imports.view',
            'player-imports.create',
            'tournaments.view',
            'tournaments.create',
            'tournaments.update',
            'tournaments.delete',
            'tournament-registrations.view',
            'tournament-registrations.create',
            'tournament-registrations.update',
            'tournament-registrations.delete',
            'tournament-modifications.view',
            'tournament-modifications.create',
            'fixtures.view',
            'fixtures.generate',
            'matchdays.view',
            'matchdays.create',
            'matchdays.update',
            'match-reports.view',
            'match-reports.update',
            'match-reports.reopen',
            'red-cards.view',
            'red-cards.update',
            'red-card-articles.view',
            'red-card-articles.create',
            'red-card-articles.update',
            'red-card-articles.delete',
            'punishments.view',
            'punishments.create',
            'punishments.request-lift',
            'punishments.approve-lift',
            'meetings.view',
            'meetings.create',
            'meetings.update',
            'standings.view',
            'standings.adjust',
            'sports-reports.view',
            'accreditations.view',
            'accreditations.update',
            'player-habilitations.view',
            'player-habilitations.create',
            'player-habilitations.update',
            'player-habilitations.delete',
            'player-transfers.view',
            'player-transfers.create',
            'player-transfers.review',
            'player-transfers.settings',
            'league-settings.view',
            'league-settings.update',
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.delete',
            'guide_types.view',
            'guide_types.create',
            'guide_types.update',
            'guide_types.delete',
            'transport_types.view',
            'transport_types.create',
            'transport_types.update',
            'transport_types.delete',
            'activity_types.view',
            'activity_types.create',
            'activity_types.update',
            'activity_types.delete',
            'tours.view',
            'tours.create',
            'tours.edit',
            'tours.delete',
            'tours.review',
            'tours.pricing',
            'tours.availability',
            'bookings.view',
            'bookings.manage',
            'website.manage',
            'audits.view',
        ];

        foreach ($permissions as $permission) {
            Permission::query()->firstOrCreate([
                'name' => $permission,
                'guard_name' => $guard,
            ]);
        }

        $permissionModels = Permission::query()
            ->where('guard_name', $guard)
            ->whereIn('name', $permissions)
            ->get()
            ->keyBy('name');

        Permission::query()
            ->whereNotIn('name', $permissions)
            ->delete();

        Role::findOrCreate('super_admin')->syncPermissions($permissions);
        Role::findOrCreate('admin')->syncPermissions(array_values(array_diff($permissions, ['teams.approve-updates', 'match-reports.reopen', 'standings.adjust'])));
        Role::findOrCreate('comite_penas')->syncPermissions([
            'dashboard.view',
            'red-cards.view',
            'red-cards.update',
            'red-card-articles.view',
            'red-card-articles.create',
            'red-card-articles.update',
            'red-card-articles.delete',
            'punishments.view',
            'punishments.create',
            'punishments.request-lift',
        ]);
        Role::findOrCreate('comite_penas_superior')->syncPermissions([
            'dashboard.view',
            'red-cards.view',
            'red-cards.update',
            'red-card-articles.view',
            'red-card-articles.create',
            'red-card-articles.update',
            'red-card-articles.delete',
            'punishments.view',
            'punishments.create',
            'punishments.request-lift',
            'punishments.approve-lift',
        ]);

        Role::findOrCreate('super_admin', $guard)->syncPermissions($permissionModels->values());
        Role::findOrCreate('admin', $guard)->syncPermissions($permissionModels->values());

        $managerPermissions = [
            'dashboard.view',
            'users.view',
            'fingerprint-templates.view',
            'fingerprint-templates.create',
            'fingerprint-templates.update',
            'roles.view',
            'permissions.view',
            'database-backups.view',
            'database-backups.create',
            'companies.view',
            'companies.create',
            'companies.update',
            'seasons.view',
            'seasons.create',
            'seasons.update',
            'divisions.view',
            'divisions.create',
            'divisions.update',
            'courts.view',
            'courts.create',
            'courts.update',
            'teams.view',
            'teams.create',
            'teams.update',
            'players.view',
            'players.create',
            'players.update',
            'player-imports.view',
            'player-imports.create',
            'tournaments.view',
            'tournaments.create',
            'tournaments.update',
            'tournament-registrations.view',
            'tournament-registrations.create',
            'tournament-registrations.update',
            'tournament-modifications.view',
            'tournament-modifications.create',
            'fixtures.view',
            'fixtures.generate',
            'matchdays.view',
            'matchdays.create',
            'matchdays.update',
            'match-reports.view',
            'match-reports.update',
            'red-cards.view',
            'red-cards.update',
            'red-card-articles.view',
            'red-card-articles.create',
            'red-card-articles.update',
            'punishments.view',
            'punishments.create',
            'punishments.request-lift',
            'meetings.view',
            'meetings.create',
            'meetings.update',
            'standings.view',
            'sports-reports.view',
            'accreditations.view',
            'accreditations.update',
            'player-habilitations.view',
            'player-habilitations.create',
            'player-habilitations.update',
            'player-transfers.view',
            'player-transfers.create',
            'player-transfers.settings',
            'league-settings.view',
            'league-settings.update',
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.delete',
            'guide_types.view',
            'guide_types.create',
            'guide_types.update',
            'guide_types.delete',
            'transport_types.view',
            'transport_types.create',
            'transport_types.update',
            'transport_types.delete',
            'activity_types.view',
            'activity_types.create',
            'activity_types.update',
            'activity_types.delete',
            'tours.view',
            'tours.create',
            'tours.edit',
            'tours.delete',
            'tours.pricing',
            'tours.availability',
            'bookings.view',
            'bookings.manage',
            'website.manage',
            'audits.view',
        ];

        Role::findOrCreate('manager', $guard)->syncPermissions($permissionModels->only($managerPermissions)->values());

        $viewerPermissions = [
            'dashboard.view',
            'users.view',
            'fingerprint-templates.view',
            'roles.view',
            'permissions.view',
            'companies.view',
            'seasons.view',
            'divisions.view',
            'courts.view',
            'teams.view',
            'players.view',
            'player-imports.view',
            'tournaments.view',
            'tournament-registrations.view',
            'tournament-modifications.view',
            'fixtures.view',
            'matchdays.view',
            'match-reports.view',
            'red-cards.view',
            'red-card-articles.view',
            'punishments.view',
            'meetings.view',
            'standings.view',
            'sports-reports.view',
            'accreditations.view',
            'player-habilitations.view',
            'player-transfers.view',
            'league-settings.view',
            'categories.view',
            'categories.view',
            'guide_types.view',
            'transport_types.view',
            'activity_types.view',
            'tours.view',
            'bookings.view',
            'audits.view',
        ];

        Role::findOrCreate('viewer', $guard)->syncPermissions($permissionModels->only($viewerPermissions)->values());

        Role::findOrCreate('tourist', $guard)->syncPermissions([]);

        app()[PermissionRegistrar::class]->forgetCachedPermissions();
    }
}
